services:
  db:
    image: mysql:8.0
    container_name: wp_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql

  plugin-host:
    image: wordpress:6.8.3-php8.4-apache
    container_name: exhibition-manager-host
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      ANGULAR_DEV: true
    volumes:
      - ./wordpress/wp-content:/var/www/html/wp-content
      - ./exhibition-manager-menu-registration:/var/www/html/wp-content/plugins/exhibition-manager
    
  plugin-logic:
    image: node:20
    container_name: exhibition-manager-plugin-logic
    working_dir: /app
    volumes:
      - ./exhibition-manager-plugin:/app
    ports:
      - "4200:4200"
    command: >
      sh -c "npm install && npm run start -- --host=0.0.0.0 --disable-host-check"

volumes:
  db_data: